### ISSUE TITLE
Players can be tormented

### ISSUE THREAD

**Issue by leeogrady** [PlantandFoodResearch/TePukeDarts#3]
Its possible to revive a dead player and kill them in the same hand

**Comment by kiwiroy** [comment]
That isn't what happened earlier, although @jasi1986 might express other thoughts.

**Comment by BMuschamp** [comment]
What about.....   They cant be killed until they have had their turn @leeogrady

**Comment by leeogrady** [comment]
Actually i think i like the totmenting idea.
