### ISSUE TITLE
No H&S documentation

### ISSUE THREAD

**Issue by leeogrady** [PlantandFoodResearch/TePukeDarts#4]

**Comment by cagaz** [comment]
I can lend the hydralada H&S material (harness + lanyard) for the darts ...

**Comment by BMuschamp** [comment]
Added-
Treat every dart as dangerous
Always point darts in a safe direction
Identify your target beyond all doubt
Check your firing zone
Store darts safetly
Avoid alcohol and drugs when handling darts
@leeogrady @cagaz @kiwiroy
